### ISSUE TITLE
x3270-script.1 manual page

### ISSUE THREAD

**Issue by Rhialto** [pmattes/x3270#26]
Just a question: I was preparing to package suite3270-4.1ga11, and noticed that the manual page `x3270-script.1`  is no longer installed (compared to suite3270-4.0ga14-src) . Is that expected? If yes, has the information been moved elsewhere?

**Comment by Rhialto** [comment]
I see that commit c8eb4e8a2d45fd8780b7dda21de21af753dabaa8 removes it so I suppose it's intentional :)

**Comment by pmattes** [comment]
Yes, it was intentional. This information has been moved to the x3270 Wiki (https://x3270.miraheze.org/wiki/Main_Page).

The x3270-script manpage was an early attempt to summarize the scripting functionality of x3270, but it grew hopelessly out of date and was not especially useful, so I got rid of it.
