### ISSUE TITLE
x3270 -model 4 doesn't negotiate extended color & attributes to VM/SP 5 telnet 

### ISSUE THREAD

**Issue by swhobbit** [pmattes/x3270#37]
x3270 in mode 4 mode has never negotiated extended color and attributes with the TCP/IP telnet on VM/SP 5 (VM TCP/IP V2R1), but does with local (Hercules driven) port.  It also does negotiates extended color and attributes on VM/ESA 2.4 (VM TCP/IP level 320). 

I always assumed this the fault of the early generation VM TCP/IP V2R1 combined with that a physical 3279-4 didn't exist, but I recently noticed two things:
- The VM TCP/IP V2R1 binary **does** include a literal for the 3279-4
- The commercial x3270 application Reflection on an iPad **does** negotiates extended color and attributes to VM TCP/IP V2R1

Thus, the expect behavior of x3270 is to also negotiate extended color and attributes with VM TCP/IP V2R1

x270 traces of various connections 
- [vmsp-local-model4.log](https://github.com/pmattes/x3270/files/8855440/vmsp-local-model4.log) — extended colors/attributes
- [vmsp-telnet-model3.log](https://github.com/pmattes/x3270/files/8855441/vmsp-telnet-model3.log)  — extended colors/attributes
- [vmsp-telnet-model4.log](https://github.com/pmattes/x3270/files/8855442/vmsp-telnet-model4.log)  — **no** extended colors/attributes
- [vmxa-telnet-model3.log](https://github.com/pmattes/x3270/files/8855443/vmxa-telnet-model3.log)  —  extended colors/attributes
- [vmxa-telnet-model4.log](https://github.com/pmattes/x3270/files/8855444/vmxa-telnet-model4.log)  — extended colors/attributes

[reflection-model4-tcpdumpe.log](https://github.com/pmattes/x3270/files/8855426/reflection-model4-tcpdumpe.log)  — 
 extended colors/attributes
[x3270-model4-tcpdumpe.log](https://github.com/pmattes/x3270/files/8855429/x3270-model4-tcpdumpe.log)  — **no** extended colors/attributes

CMS EXEC to report VM/SP query of terminal:
[pagesize.exec.txt](https://github.com/pmattes/x3270/files/8855486/pagesize.exec.txt)

If access is desired to the TELNET port of my VM/SP system running VM TCP/IP V2R1 (or the other systems I test with), let me know.

**Comment by pmattes** [comment]
I looked at the traces, and here is my analysis.

When x3270 negotiates with the VM/SP system, it sends its terminal type as IBM-3279-4-E (a color display). When Reflection negotiates with the VM/SP system, it sends its terminal type as IBM-3278-4-E (a monochrome display).

The host responds to x3270 by finishing TN3270 negotiation and painting the login screen. The host responds to Reflection by finishing TN3270 negotiation, then sending a Query structured field. Reflection responds with information about the extended colors and attributes it supports. Then the host paints the login screen. The host does not know about x3270's extended color and attribute support because it never asks about it. And it has to ask -- the terminal emulator cannot volunteer this information.

So apparently when the VM/SP host sees the terminal type as IBM-3279-4-E from x3270, it gets confused and decides to ignore the '-E' suffix, which is the thing that signals that the terminal supports the Query structured field.

I can't change x3270's default behavior here, because it has been this way for quite some time and there have not been any complaints about it until now. But there is an easy workaround. Add this command-line parameter:
&nbsp;&nbsp;-tn IBM-3278-4-E

That should make the host happy.

**Comment by swhobbit** [comment]
**FYI**: It also be noted that under VM/SP 5 (TCP/IP Netstat V2R1), to get extended color/attributes a model 5 (132 columns by 27 rows) requires a similar parameter:  `-tn IBM-3278-5-E` 

(You can close this again, or better yet leave it open until the documentation is updated.)

**Comment by swhobbit** [comment]
> That should make the host happy.

More importantly, it makes the user (me!) happy.  :-)
